### ISSUE TITLE
Update facts

### ISSUE THREAD

**Issue by sprat** [Oefenweb/ansible-hostname#15]
I've noticed a problem: after the hostname update, the ansible facts are not updated and so the subsequent roles depending on the `ansible_domain` or `ansible_fqdn` variables still use the old  domain. I was expecting the new domain were used right after using this role.

**Comment by sprat** [comment]
I've solved the problem in my playbook with the following task:
```yaml
- name: Update hostname/domain facts
      set_fact:
        ansible_hostname: "{{ hostname_hostname_short }}"
        ansible_domain: "{{ hostname_hostname.split('.', 1)[1] }}"
        ansible_fqdn: "{{ hostname_hostname }}"
      when: ansible_fqdn != hostname_hostname
```
